version: "3"

services:
  db:
    image: postgres
    container_name: cinema_db
    ports: ["5435:5432"]
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "cinema"
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9011:9000"
      - "9012:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: cinema_access_key
      MINIO_ROOT_PASSWORD: cinema_secret_key
#      MINIO_ACCESS_KEY: cinema_access_key
#      MINIO_SECRET_KEY: cinema_secret_key
    restart: always

volumes:
  postgres-data:
  minio-data: