version: "3"

services:
  db:
    image: postgres
    container_name: cinema_db
    ports: ["5435:5432"]
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "cinema"
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data: